Peter
theycallmepeter/DreamTeamWAD2 pull request #14
Opened 2019-03-09 19:13 UTC by theycallmepeter

Implemented adding a question functionality
Implemented rating a question functionality
Changed question slug generation to random instead of pk abuse 👎 
Please be gentle 😊

2019-03-09 20:47 UTC, JoseAntRodriguez commented
Works for me as far as I can tell. Although you don't actually need to change the slug generation, saving twice as is already done in the views.py generates the slug from the primary key

2019-03-10 00:39 UTC, theycallmepeter commented
> Works for me as far as I can tell. Although you don't actually need to change the slug generation, saving twice as is already done in the views.py generates the slug from the primary key

I forgot to remove the saving twice part, my bad.

2019-03-10 01:06 UTC, Hodobox commented
will review first thing tomorrow

2019-03-10 12:53 UTC, Hodobox requested changes

2019-03-10 12:53 UTC, Hodobox commented on TODO.md
> -# Stuff that needs doing
Why was this deleted?

2019-03-10 12:53 UTC, Hodobox commented on Gliocas/gliocas_app/views.py
> +    elif like == '1':
```suggestion
   else:
        upvote = UpvoteQuestion.objects.create(question=question, user=user, positive=(like == '1'))
        upvote.save()
        print( 'upvoted' if (like == '1') else 'downvoted')
```

2019-03-10 12:53 UTC, Hodobox commented on Gliocas/gliocas_app/models.py
> +    # def save(self, *args, **kwargs):
remove unused code

2019-03-10 12:53 UTC, Hodobox commented on Gliocas/gliocas_app/models.py
> +    slug = models.SlugField(max_length=8, default=get_random_string(length=9), unique=True)
this makes Django run get_random_string(length=9) once at beginning of migration, and then all questions get the same slug, so UNIQUE constraint fails (did you not try running populate.py?) remove (length=9) so it uses the function to get a new value everytime instead.

```suggestion
    slug = models.SlugField(max_length=8, default=get_random_string, unique=True)
```

2019-03-10 12:53 UTC, Hodobox commented on Gliocas/gliocas_app/views.py
> +        #TODO implement with user = request.user.pk after auth is finished
remove #TODO?

2019-03-10 12:53 UTC, Hodobox commented on Gliocas/gliocas_app/forms.py
> +		self.fields['poster'].initial = 'rango'
probably want to use the self.user.get_username() around here, no? use what you do want to use and remove commented ones.

2019-03-10 12:53 UTC, Hodobox commented on Gliocas/gliocas_app/urls.py
> +    url(r'^subject/(?P<subject_slug>[\w\-]+)/(?P<course_slug>[\w\-]+)/(?P<question_slug>[\w\-]+)/like/(?P<like>[\d])/$', views.like_question, name='like_question'),
is liking a question an unfinished feature? if so, don't merge that part of the branch into master. Because currently, this site seems to me inaccessible from the website (I would expect there to be a upvote/downvote link on the subject/course/question/ page), and how this works atm is that if you type the url yourself (or in the future, if you get to this url), then refreshing that page will upvote/downvote/remove_vote over and over again (which I'm sure the user will not be intending to do when he types this link/refreshes the page).

2019-03-10 14:37 UTC, theycallmepeter commented on Gliocas/gliocas_app/urls.py
> +    url(r'^subject/(?P<subject_slug>[\w\-]+)/(?P<course_slug>[\w\-]+)/(?P<question_slug>[\w\-]+)/like/(?P<like>[\d])/$', views.like_question, name='like_question'),
Why would it work that way? Did you look at the view? It toggles. If the user already upvoted/downvoted, it just removes it.

2019-03-10 14:56 UTC, theycallmepeter commented on TODO.md
> -# Stuff that needs doing
No idea, readded.

2019-03-10 14:57 UTC, theycallmepeter commented on Gliocas/gliocas_app/urls.py
> +    url(r'^subject/(?P<subject_slug>[\w\-]+)/(?P<course_slug>[\w\-]+)/(?P<question_slug>[\w\-]+)/like/(?P<like>[\d])/$', views.like_question, name='like_question'),
I also added the links.

2019-03-10 15:29 UTC, Hodobox approved these changes
OK, but 
1) refreshing the /like/# page, by itself, changing the database should be fixed
2) I like that when you click Like, and Like again, it removes the upvote. But if I clicked Like, and then Dislike, it still only removes the upvote, I think it should give it a downvote as well. i.e. something like if_exists() and same_value(): remove, elif exists() and different_value() store_new_value(), in that part of the code.

Please implement these fixes and pull request them in the next few days.

2019-03-10 15:37 UTC, merged