Peter
theycallmepeter/DreamTeamWAD2 pull request #21
Opened 2019-03-17 21:19 UTC by theycallmepeter

Replies are done, also possible to add a course now, adding a subject was buggy so I removed it and as others have said it should be only admins that are able to add subjects.

2019-03-17 22:05 UTC, theycallmepeter commented
Gonna merge with newest master first. Then create a request.

2019-03-18 10:16 UTC, JoseAntRodriguez commented
Testing everything, looks like it works for me, except for adding subject. Just a couple of things: are we sure we want users to be able to add subjects and courses? UofG has only certain subjects and courses, so we shouldn't let users create them at will in our website. Also, I know this is a presentation issue and it should probably be handed by Cho but right now users can't know if they've liked or disliked a question/answer/reply before and the website doesn't give any feedback when, say, the users undo a previous like or dislike

2019-03-18 13:53 UTC, Hodobox commented
I agree with Pepe, I believe this has a simple fix: https://stackoverflow.com/questions/12003736/django-login-required-decorator-for-a-superuser for adding course/subject.

2019-03-18 14:06 UTC, Hodobox requested changes

2019-03-18 14:06 UTC, Hodobox commented on Gliocas/gliocas_app/views.py
> +        answer = None
```suggestion
        answer = None
        question = None
```

2019-03-18 14:06 UTC, Hodobox commented on Gliocas/gliocas_app/views.py
> +@login_required
the user_passes_test .is_superuser please to add course and subject

2019-03-18 14:06 UTC, Hodobox commented on Gliocas/searchStdl.py
> +import os
remove file because (correct me if I'm wrong) this was just a standalone file to test search, and for our site it's in search.py (you can try and find the comment about this from I think Pepe's pull request for search)

2019-03-18 14:57 UTC, Hodobox approved these changes

2019-03-18 14:58 UTC, merged

2019-03-18 15:00 UTC, Hodobox commented
you forgot to import the decorator...